version: 'version 1.0.0'

networks:
  img2map-network:
    driver: bridge
  #This is the network that the containers will use to communicate with each other

services:
  img2map-api:
    #Uvicorn server running python FastAPI
    container_name: Img2Map-API
    build:
      context: ./backend
      dockerfile: /docker/prod.Dockerfile
    expose:
      - "8000:8000"
    networks:
      - img2map-network
  
  next-app:
    container_name: Img2Map-Website
    build:
      context: ./frontend
      dockerfile: /docker/prod.Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    networks:
      - img2map-network
    depends_on:
      - serviceName: img2map-api
        condition: service_healthy
  