name: buildtesting for dev
on:
  push:
    #ignore the push event on the dev branch
    branches-ignore:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: build with docker-compose
              run: docker-compose -f docker-compose.dev.yml up --build
                
                
