name: buildtesting for dev
on:
  push:
    #ignore the push event on the dev branch
    branches-ignore:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build and run backend container
              run: |
                docker build ./backend -f /docker/dev.Dockerfile -t backend
                docker run backend
            
            - name: Frontend Build and test with docker
              run: |
                docker build ./frontend -f /docker/dev.Dockerfile -t frontend  
                docker run frontend

            - name: build with docker-compose
              run: docker-compose -f docker-compose.dev.yml up --build
                
                
