name: Deploy

on:
  push:
    branches:
      - dev
    tags:
      - 'v.[0-9]+.[0-9]+.[0-9]+(?!-dev)'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./path/to/Dockerfile
          push: true
          tags: |
            registry.heroku.com/img2map/web
          build-args: |
            NODE_ENV=production

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u _ -p $(heroku auth:token) registry.heroku.com

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/img2map/web

      - name: Release Docker image to Heroku
        run: heroku container:release web --app img2map
