name: Deploy

on:
  push:
    branches:
      - dev
    tags:
      - 'v.[0-9]+.[0-9]+.[0-9]+(?!-dev)'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker-compose -f ./docker-compose.yml build

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u _ -p $(heroku auth:token) registry.heroku.com

      - name: Push Docker images to Heroku
        run: docker-compose -f ./docker-compose.yml push

      - name: Release Docker images to Heroku
        run: heroku container:release web --app img2map
